'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cliente
    Public Property ID As String
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property RUT As String
    Public Property Comuna As String
    Public Property Direccion As String
    Public Property Email As String
    Public Property Clave As String

End Class
