'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class datosTransferencia
    Public Property Nombre As String
    Public Property Rut As String
    Public Property NumeroDeCuenta As String
    Public Property Email As String
    Public Property NombreBanco As String

End Class
